name: auth_toolkit
description: A new Flutter package project.
version: 0.5.3
homepage: https://github.com/sit-michael/auth_toolkit.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_inappwebview: 5.4.4+3 
  flutter_secure_storage: ^6.0.0
  jwt_decoder: ^2.0.1
  logging: ^1.1.0
  package_info_plus: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
