name: auth_toolkit
description: A new Flutter package project.
version: 0.5.0
homepage: https://github.com/sit-michael/flutter-auth_toolkit.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  crypto: ^3.0.2
  jwt_decoder: ^2.0.1
  logging: ^1.1.0
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
